### ISSUE TITLE
irs-line width

### ISSUE THREAD

**Issue by jeremyjumeau** [IonDen/ion.rangeSlider#167]
Hi Ion,
First of all, congrats for you plugin, it's awesome!

I open that issue because I encountered a weird behavior when I used the slider in full size on a small window: the `irs-line` span appeared small than the `irs-slider` and `irs-grid`.

Is the classbelow really need to be overflow: hidden?

``` css
.irs-line {
        overflow: hidden;
}
```

I can PR that issue if relevant,
Thanks,
Jeremy
