### ISSUE TITLE
Two sliders with different skin

### ISSUE THREAD

**Issue by humbertorodrigues** [IonDen/ion.rangeSlider#388]
Would be very nice if I could set which skin should be used when I set a slider.
I mean, I would like to have 2 sliders at the same document and each slider with a different skin.
As I could see, this isn't an option avaiable. Am I wrong?

**Comment by IonDen** [comment]
Multi skin support will be added only in 3.0 version, which is under development now.

If you want do do this with current version, you should create your own skins with container dependency. Like this:
```css
.color1 .irs-something {
    color: #000;
}

.color2 .irs-something {
    color: #999;
}
```
