### ISSUE TITLE
Toolbar colors

### ISSUE THREAD

**Issue by ocp1000** [IonDen/ion.rangeSlider#699]
Hello,
Is it possible to change the toolbar color and the min/max colors?

**Comment by IonDen** [comment]
Hi, if you can see here:
http://ionden.com/a/plugins/ion.rangeSlider/skins.html

You can have different skins.

So, nobody stops you from creating a new skin, or altering one of current skins to fit your needs.
What can't be done with plugin API, can be done with CSS.

**Comment by IonDen** [comment]
There's no color option in the config, colors come from the skin's stylesheet. Start with one of the built in skins:

```js
$("#range").ionRangeSlider({
    skin: "big"
});
```

If none of them match what you need, override the classes for that skin in your own CSS, loaded after ion.rangeSlider's stylesheet. The bar and handles use `.irs-bar` and `.irs-handle`, the min/max labels use `.irs-min` and `.irs-max`:

```css
.irs--big .irs-bar,
.irs--big .irs-handle {
    background: #ff6600;
}
.irs--big .irs-min,
.irs--big .irs-max {
    color: #333;
}
```

That covers everything the skins page (skins.html) shows.
